shopstream:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: FIARMWM-NQ08270
      user: USERNAME
      password: SNOWFLAKE_PASSWORD
      role: ACCOUNTADMIN
      database: SHOPSTREAM_DB
      warehouse: SHOPSTREAM_WH
      schema: STAGING
      threads: 4






### Snowflake Account Identifier Kaise Pata Karo?

