-- ============================================================
-- ShopStream Analytics — Snowflake Setup
-- Run this as ACCOUNTADMIN once to set up entire environment
-- ============================================================

-- ─── STEP 1: Create Databases ────────────────────────────────
CREATE DATABASE IF NOT EXISTS SHOPSTREAM_DB
    COMMENT = 'ShopStream Analytics main database';

-- Schemas (layers)
CREATE SCHEMA IF NOT EXISTS SHOPSTREAM_DB.RAW
    COMMENT = 'Raw data landed from S3 via ingestion';

CREATE SCHEMA IF NOT EXISTS SHOPSTREAM_DB.STAGING
    COMMENT = 'Cleaned, typed data - dbt staging models';

CREATE SCHEMA IF NOT EXISTS SHOPSTREAM_DB.INTERMEDIATE
    COMMENT = 'Business logic transformations';

CREATE SCHEMA IF NOT EXISTS SHOPSTREAM_DB.MARTS
    COMMENT = 'Final analytics-ready tables for dashboards';

CREATE SCHEMA IF NOT EXISTS SHOPSTREAM_DB.AUDIT
    COMMENT = 'Pipeline run logs and data quality results';

-- ─── STEP 2: Create Warehouse ────────────────────────────────
CREATE WAREHOUSE IF NOT EXISTS SHOPSTREAM_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'ShopStream transformation warehouse';

-- ─── STEP 3: Roles ───────────────────────────────────────────
CREATE ROLE IF NOT EXISTS SHOPSTREAM_LOADER
    COMMENT = 'Ingestion scripts - S3 to RAW schema';

CREATE ROLE IF NOT EXISTS SHOPSTREAM_TRANSFORMER
    COMMENT = 'dbt and Spark - RAW to MARTS';

CREATE ROLE IF NOT EXISTS SHOPSTREAM_REPORTER
    COMMENT = 'Dashboard/BI tools - read-only MARTS';

-- Grant privileges
GRANT USAGE ON WAREHOUSE SHOPSTREAM_WH TO ROLE SHOPSTREAM_LOADER;
GRANT USAGE ON WAREHOUSE SHOPSTREAM_WH TO ROLE SHOPSTREAM_TRANSFORMER;
GRANT USAGE ON WAREHOUSE SHOPSTREAM_WH TO ROLE SHOPSTREAM_REPORTER;

GRANT USAGE ON DATABASE SHOPSTREAM_DB TO ROLE SHOPSTREAM_LOADER;
GRANT USAGE ON DATABASE SHOPSTREAM_DB TO ROLE SHOPSTREAM_TRANSFORMER;
GRANT USAGE ON DATABASE SHOPSTREAM_DB TO ROLE SHOPSTREAM_REPORTER;

-- Loader: write to RAW only
GRANT ALL ON SCHEMA SHOPSTREAM_DB.RAW TO ROLE SHOPSTREAM_LOADER;

-- Transformer: read RAW, write STAGING/INTERMEDIATE/MARTS
GRANT SELECT ON ALL TABLES IN SCHEMA SHOPSTREAM_DB.RAW TO ROLE SHOPSTREAM_TRANSFORMER;
GRANT ALL ON SCHEMA SHOPSTREAM_DB.STAGING TO ROLE SHOPSTREAM_TRANSFORMER;
GRANT ALL ON SCHEMA SHOPSTREAM_DB.INTERMEDIATE TO ROLE SHOPSTREAM_TRANSFORMER;
GRANT ALL ON SCHEMA SHOPSTREAM_DB.MARTS TO ROLE SHOPSTREAM_TRANSFORMER;
GRANT ALL ON SCHEMA SHOPSTREAM_DB.AUDIT TO ROLE SHOPSTREAM_TRANSFORMER;

-- Reporter: read MARTS only
GRANT SELECT ON ALL TABLES IN SCHEMA SHOPSTREAM_DB.MARTS TO ROLE SHOPSTREAM_REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SHOPSTREAM_DB.MARTS TO ROLE SHOPSTREAM_REPORTER;
